# Ruff configuration file

[lint]
select = ["ALL"]  # Enable all rules
ignore = ["TRY300"]  # Ignore suggestion about moving return statements to else blocks
per-file-ignores = { "tests/*.py" = ["INP001", "S101", "ANN401", "ANN002", "ANN003"] }
